import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// One autogenerated sidebar over the whole content root. Ordering and grouping stay in
// the documents themselves, so the sidebar cannot drift from what docs/ actually holds.
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
