/** Stamped into every artifact as `compiledWith`, so an artifact records what produced it. */
// Generated by scripts/sync-core-version.mjs from packages/core/package.json. Do not edit.
export const NUBBIN_VERSION = "0.1.0-rc.4";
