// The exact text of `packages/core/src/version.constants.ts`, derived from the manifest.
//
// One home for the template, because two would drift: `sync-core-version.mjs` writes this file and
// `tests/coreVersionStamp.test.mjs` asserts it. A generator and an assertion that each carry their
// own copy of the expected output agree with each other and with nothing else.

import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export async function coreVersionConstant() {
  const manifest = join(ROOT, "packages/core/package.json");
  const { version } = JSON.parse(await readFile(manifest, "utf8"));
  const text = `/** Stamped into every artifact as \`compiledWith\`, so an artifact records what produced it. */
// Generated by scripts/sync-core-version.mjs from packages/core/package.json. Do not edit.
export const NUBBIN_VERSION = ${JSON.stringify(version)};
`;
  return { version, text, file: join(ROOT, "packages/core/src/version.constants.ts") };
}
